### PR TITLE
Add debug information to output

### PR DESCRIPTION
**Pull request by gzzsound**
Add debug information if a group of tests is failing

Please sign-off: @Simbul @lukaso @dragosmiron

### CODE REVIEW

**Comment by lukaso** [comment]
Should there be tests for this new functionality? If there can be, maybe we can get this merged upstream (unlike the current rutabaga and turnip support).

**Comment by dragosmiron** [comment]
signed off by @dragosmiron.
would be nice to have one test :)

**Comment by dcoxall** [comment]
We can merge these individual changes into upstream (with tests) but our fork also includes more major changes (less features) such as including `.feature` files in the test groups which is more of a custom feature.

**Comment by dragosmiron** [comment]
still this change could be PRd upstream

**Comment by lukaso** [comment]
The other major changes for supporting turnip and rutabaga would centre
around making the file search options flexible and allowing the timing code
to use all the file names. It's probably a day or two of work which is why
I (and previous people) didn't/weren't able to do it.

Lukas Oberhuber
Chief Technology Officer
+44 (0)20 7920 8026 <+44+(0)20+7920+8026>
lukas.oberhuber@simplybusiness.co.uk
www.simplybusiness.co.uk
#1 Best Company to Work For in the UK 2015.
Shortlisted and winner of multiple awards.
Visit our awards and recognition page
<http://www.simplybusiness.co.uk/about-us/awards/>
Need more help?
You can find plenty of information and hopefully the answers to your
questions on our searchable support page
<https://simplybusiness.zendesk.com/home>, or contact us online
<https://www.simplybusiness.co.uk/support/> or via social media
<http://www.simplybusiness.co.uk/social/>. Company Registration Number:
03967717

**Comment by Simbul** [comment]
@gzzsound posted a sample output of this command on Slack:

```
Failed command:	TEST_ENV_NUMBER=4;export TEST_ENV_NUMBER;PARALLEL_TEST_GROUPS=4;export PARALLEL_TEST_GROUPS;bundle exec rspec  --color --tty -O .rspec_parallel spec/controllers/backoffice/business_rules/amend_creation_spec.rb spec/controllers/backoffice/business_rules/renewals_creation_spec.rb spec/journey/renewal_buy_online/quote_details/endorsements_action_spec.rb spec/lib/ci5/pages/page_section_spec.rb spec/models/policy/docs/cancellation_spec.rb spec/models/policy/lifecycle/finrec_calculation_spec.rb spec/models/session_spec.rb spec/models/transaction/fiscal_transaction_spec.rb
Seed used:	58489
```

I think it would help to make the message a bit clearer. It's not immediately clear to me what the command is for or why we're printing the list of files and those environment variables.

Maybe we could say:
```
Tests have failed for a parallel_test group. Use the following command to run the group again:
TEST_ENV_NUMBER=4;export...
Add "--seed 58489" to the command to run tests in the same order.
```

**Comment by dragosmiron** [comment]
not sure -O .rspec_parallel would work for rspec to run the same command

**Comment by Simbul** [comment]
As I understand it, the whole point of printing out the command is to ensure we can re-run. If the command we print out doesn't allow for that, we need to print out something else :smiley:

**Comment by gzzsound** [comment]
The idea is to print the failed command. So the message could be something like that:

Tests have failed for a parallel_test group. The info about the failed command are:
Command: 
Seed used:

If we want provide a command that we can run we have to parse the failed command and extract the information that we need. My suggestion, to release the beaver, is that we can proceed through iterations and improve the output in a different PR.

**Comment by Simbul** [comment]
Just tried running the command with @gzzsound and it looks like everything is working as it should.

```
TEST_ENV_NUMBER=4;export TEST_ENV_NUMBER;PARALLEL_TEST_GROUPS=4;export PARALLEL_TEST_GROUPS;bundle exec rspec  --color --tty -O .rspec_parallel spec/controllers/backoffice/business_rules/amend_creation_spec.rb spec/controllers/backoffice/business_rules/renewals_creation_spec.rb spec/journey/renewal_buy_online/quote_details/endorsements_action_spec.rb spec/lib/ci5/pages/page_section_spec.rb spec/models/policy/docs/cancellation_spec.rb spec/models/policy/lifecycle/finrec_calculation_spec.rb spec/models/session_spec.rb spec/models/transaction/fiscal_transaction_spec.rb

Run options: exclude {:shakedown_server=>true, :penetration=>true, :configuration=>true, :wip=>true}
...................................................

Finished in 7.67 seconds
51 examples, 0 failures

2 deprecations logged to /dev/null
```

Unless there's some sneaky corner case we're not seeing, I'd go ahead with my suggestion above.

**Comment by lukaso** [comment]
I'm waiting to signoff for the small refactor into a method that @gzzsound was going to do and for the test (or indication it's not possible).

**Comment by lukaso** [comment]
I'm really pretty sure the test failures aren't being caused by the random
seed though.

**Comment by gzzsound** [comment]
Pushed but without adding the test. I will add the test if we want to open a PR upstream. 
The messages displayed will be:

Tests have failed for a parallel_test group. Use the following command to run the group again:

TEST_ENV_NUMBER=4;export TEST_ENV_NUMBER;PARALLEL_TEST_GROUPS=4;export PARALLEL_TEST_GROUPS;bundle exec rspec  --color --tty -O .rspec_parallel spec/concerns/auditable_controller_concern_spec.rb .......

Checkout your local branch to the deployed SHA and add '--seed 39025' to the command to run tests in the same order.

**Comment by Simbul** [comment]
By the way, @lukaso, I have a feeling `ParallelTests::RSpec::RuntimeLogger` in `.rspec_parallel` may have stopped working.

On my machine, after running `bundle exec rake`, `parallel_runtime_rspec.log` only contains:

```
$ cat tmp/parallel_runtime_rspec.log
Run options: exclude {:shakedown_server=>true, :penetration=>true, :configuration=>true, :wip=>true}
Run options: exclude {:shakedown_server=>true, :penetration=>true, :configuration=>true, :wip=>true}
Run options: exclude {:shakedown_server=>true, :penetration=>true, :configuration=>true, :wip=>true}
Run options: exclude {:shakedown_server=>true, :penetration=>true, :configuration=>true, :wip=>true}
```

Shouldn't it have something more to be able to rearrange tests across cores?

**Comment by lukaso** [comment]
@Simbul If you cancel your tests during a run, that's what you get. You have to let the tests run the whole way through...

**Comment by lukaso** [comment]
Signed-off-by: @lukaso, but really should have a test for new functionality...

**Comment by Simbul** [comment]
> @Simbul If you cancel your tests during a run, that's what you get. You have to let the tests run the whole way through...

That's what I did. They ran the whole way through and there were no failures, but still nothing was logged.

**Pull request merged**
